### ISSUE TITLE
'QPainter' has no attribute 'LosslessImageRendering'

### ISSUE THREAD

**Issue by madprops** [sertraline/chizuhoru#3]
Just found out about this interesting project and I'm testing it.
I think I found a bug, which seems to happen when I use the shaded rectangle icon selection tool:

```
[12:46:36] /home/yo/table/chizuhoru
λ ./chizuhoru 
[12:47:40] /home/yo/table/chizuhoru
λ qt5ct: using qt5ct plugin
qt5ct: D-Bus system tray: no
qt5ct: palette support is disabled
Traceback (most recent call last):
  File "/home/yo/table/chizuhoru/py/screen_window.py", line 709, in mouseReleaseEvent
    painter.setRenderHint(QPainter.LosslessImageRendering)
AttributeError: type object 'QPainter' has no attribute 'LosslessImageRendering'
QPaintDevice: Cannot destroy paint device that is being painted
```

Btw it seems in the gif demo that it can autoselect windows, like sharex does? That would be cool

I like how the imgur upload works, would be nice to have an option to copy the jpg version to the clipboard instead though, for lower file sizes.

Good stuff, I could see myself using this instead of flameshot

**Comment by sertraline** [comment]
Thanks! 'LosslessImageRendering' has been introduced in Qt 5.13, so if your version of Qt is older than that it won't work. I was thinking to reserve this hint for the future but it still doesn't have any use so could as well be removed.

Autoselection uses Xlib calls and in such form it only works properly in KDE or LXQt which give correct window coordinates. In GTK window decorations are rendered inseparable from windows, meaning shadows and everything below them will be grabbed as well. I'm not sure when I'll have time to learn GTK api to get windows properly.

As for jpg, Qt works with png by default and jpg needs a separate plugin. I wanted to avoid dealing with package manager but I could make it optional and let the user decide in the settings.

**Comment by madprops** [comment]
Just for some information
This is the output of 'qmake --version'
>Using Qt version 5.14.1 in /usr/lib/x86_64-linux-gnu

Also I'm using awesomewm window manager, which I had to tweak a bit to make the "freeze" work correctly, basically I toggled 'fullscreen' on the window twice to put it in place, else it would have a bit of an offset.

**Comment by madprops** [comment]
It seems it's not crashing anymore when using the blur tool
